FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime

RUN apt-get update && apt-get install -y git libglib2.0-0 libsm6 libxrender1 libxext6 wget && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app
CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "deploy.app:app", "--host", "0.0.0.0", "--port", "8000"]
